package labosns;
// Generated Oct 27, 2019 7:19:04 PM by Hibernate Tools 4.3.1


import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * GodisnjiOdmori generated by hbm2java
 */
@Entity
@Table(name="godisnji_odmori"
    ,catalog="laboratorija"
)
public class GodisnjiOdmori  implements java.io.Serializable {
    @Transient
    private PropertyChangeSupport changeSupport = new PropertyChangeSupport(this);


@Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
     private Integer id;
@Column(name="Pocetakodmora", nullable=false, length=45)
     private String pocetakOdmora;
@Column(name="Krajodmora", nullable=false, length=45)
     private String krajOdmora;
@Column(name="Ime", nullable=false, length=45)
     private String ime;

    public GodisnjiOdmori() {
    }

    public GodisnjiOdmori(String pocetakOdmora, String krajOdmora, String ime) {
       this.pocetakOdmora = pocetakOdmora;
       this.krajOdmora = krajOdmora;
       this.ime = ime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        Integer oldId = this.id;
        this.id = id;
        changeSupport.firePropertyChange("id", oldId, id);
    }

    
    public String getPocetakOdmora() {
        return this.pocetakOdmora;
    }
    
    public void setPocetakOdmora(String pocetakOdmora) {
        String oldPocetakOdmora = this.pocetakOdmora;
        this.pocetakOdmora = pocetakOdmora;
        changeSupport.firePropertyChange("pocetakOdmora", oldPocetakOdmora, pocetakOdmora);
    }

    
    public String getKrajOdmora() {
        return this.krajOdmora;
    }
    
    public void setKrajOdmora(String krajOdmora) {
        String oldKrajOdmora = this.krajOdmora;
        this.krajOdmora = krajOdmora;
        changeSupport.firePropertyChange("krajOdmora", oldKrajOdmora, krajOdmora);
    }

    
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        String oldIme = this.ime;
        this.ime = ime;
        changeSupport.firePropertyChange("ime", oldIme, ime);
    }

    public void addPropertyChangeListener(PropertyChangeListener listener) {
        changeSupport.addPropertyChangeListener(listener);
    }

    public void removePropertyChangeListener(PropertyChangeListener listener) {
        changeSupport.removePropertyChangeListener(listener);
    }




}


