package labosns;
// Generated Oct 27, 2019 7:19:04 PM by Hibernate Tools 4.3.1


import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Lokaliteti generated by hbm2java
 */
@Entity
@Table(name="lokaliteti"
    ,catalog="laboratorija"
)
public class Lokaliteti  implements java.io.Serializable {
    @Transient
    private PropertyChangeSupport changeSupport = new PropertyChangeSupport(this);


@Id
    @Column(name="id", unique=true, nullable=false)
     private int id;
@Column(name="Datum")
     private String datum;
@Column(name="Pofalici", length=45)
     private String pofalici;
@Column(name="Velesici", length=45)
     private String velesici;
@Column(name="TrgHeroja", length=45)
     private String trgHeroja;

    public Lokaliteti() {
    }

	
    public Lokaliteti(int id) {
        this.id = id;
    }
    public Lokaliteti( String datum, String pofalici, String velesici, String trgHeroja) {
   
       this.datum = datum;
       this.pofalici = pofalici;
       this.velesici = velesici;
       this.trgHeroja = trgHeroja;
    }

    
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        int oldId = this.id;
        this.id = id;
        changeSupport.firePropertyChange("id", oldId, id);
    }

    
    public String getDatum() {
        return this.datum;
    }
    
    public void setDatum(String datum) {
        String oldDatum = this.datum;
        this.datum = datum;
        changeSupport.firePropertyChange("datum", oldDatum, datum);
    }

    
    public String getPofalici() {
        return this.pofalici;
    }
    
    public void setPofalici(String pofalici) {
        String oldPofalici = this.pofalici;
        this.pofalici = pofalici;
        changeSupport.firePropertyChange("pofalici", oldPofalici, pofalici);
    }

    
    public String getVelesici() {
        return this.velesici;
    }
    
    public void setVelesici(String velesici) {
        String oldVelesici = this.velesici;
        this.velesici = velesici;
        changeSupport.firePropertyChange("velesici", oldVelesici, velesici);
    }

    
    public String getTrgHeroja() {
        return this.trgHeroja;
    }
    
    public void setTrgHeroja(String trgHeroja) {
        String oldTrgHeroja = this.trgHeroja;
        this.trgHeroja = trgHeroja;
        changeSupport.firePropertyChange("trgHeroja", oldTrgHeroja, trgHeroja);
    }

    public void addPropertyChangeListener(PropertyChangeListener listener) {
        changeSupport.addPropertyChangeListener(listener);
    }

    public void removePropertyChangeListener(PropertyChangeListener listener) {
        changeSupport.removePropertyChangeListener(listener);
    }




}


