package labosns;
// Generated Oct 27, 2019 7:19:04 PM by Hibernate Tools 4.3.1


import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Nedelje generated by hbm2java
 */
@Entity
@Table(name="nedelje"
    ,catalog="laboratorija"
)
public class Nedelje  implements java.io.Serializable {
    @Transient
    private PropertyChangeSupport changeSupport = new PropertyChangeSupport(this);


@Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
     private Integer id;
@Column(name="Datum", nullable=false, length=45)
     private String datum;
@Column(name="Prvasmjena", nullable=false, length=45)
     private String prvaSmjena;
@Column(name="Drugasmjena", nullable=false, length=45)
     private String drugaSmjena;

    public Nedelje() {
    }

    public Nedelje(String datum, String prvaSmjena, String drugaSmjena) {
       this.datum = datum;
       this.prvaSmjena = prvaSmjena;
       this.drugaSmjena = drugaSmjena;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        Integer oldId = this.id;
        this.id = id;
        changeSupport.firePropertyChange("id", oldId, id);
    }

    
    public String getDatum() {
        return this.datum;
    }
    
    public void setDatum(String datum) {
        String oldDatum = this.datum;
        this.datum = datum;
        changeSupport.firePropertyChange("datum", oldDatum, datum);
    }

    
    public String getPrvaSmjena() {
        return this.prvaSmjena;
    }
    
    public void setPrvaSmjena(String prvaSmjena) {
        String oldPrvaSmjena = this.prvaSmjena;
        this.prvaSmjena = prvaSmjena;
        changeSupport.firePropertyChange("prvaSmjena", oldPrvaSmjena, prvaSmjena);
    }

    
    public String getDrugaSmjena() {
        return this.drugaSmjena;
    }
    
    public void setDrugaSmjena(String drugaSmjena) {
        String oldDrugaSmjena = this.drugaSmjena;
        this.drugaSmjena = drugaSmjena;
        changeSupport.firePropertyChange("drugaSmjena", oldDrugaSmjena, drugaSmjena);
    }

    public void addPropertyChangeListener(PropertyChangeListener listener) {
        changeSupport.addPropertyChangeListener(listener);
    }

    public void removePropertyChangeListener(PropertyChangeListener listener) {
        changeSupport.removePropertyChangeListener(listener);
    }




}


