package labosns;
// Generated Oct 27, 2019 7:19:04 PM by Hibernate Tools 4.3.1


import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Zaposlenici generated by hbm2java
 */
@Entity
@Table(name="zaposlenici"
    ,catalog="laboratorija"
)
public class Zaposlenici  implements java.io.Serializable {
    @Transient
    private PropertyChangeSupport changeSupport = new PropertyChangeSupport(this);


@Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
     private Integer id;
@Column(name="Imeiprexime", length=45)
     private String imeIPrexime;
@Column(name="Adresa", length=45)
     private String adresa;
@Column(name="Mobitel", length=45)
     private String mobitel;

    public Zaposlenici() {
    }

    public Zaposlenici(String imeIPrexime, String adresa, String mobitel) {
       this.imeIPrexime = imeIPrexime;
       this.adresa = adresa;
       this.mobitel = mobitel;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        Integer oldId = this.id;
        this.id = id;
        changeSupport.firePropertyChange("id", oldId, id);
    }

    
    public String getImeIPrexime() {
        return this.imeIPrexime;
    }
    
    public void setImeIPrexime(String imeIPrexime) {
        String oldImeIPrexime = this.imeIPrexime;
        this.imeIPrexime = imeIPrexime;
        changeSupport.firePropertyChange("imeIPrexime", oldImeIPrexime, imeIPrexime);
    }

    
    public String getAdresa() {
        return this.adresa;
    }
    
    public void setAdresa(String adresa) {
        String oldAdresa = this.adresa;
        this.adresa = adresa;
        changeSupport.firePropertyChange("adresa", oldAdresa, adresa);
    }

    
    public String getMobitel() {
        return this.mobitel;
    }
    
    public void setMobitel(String mobitel) {
        String oldMobitel = this.mobitel;
        this.mobitel = mobitel;
        changeSupport.firePropertyChange("mobitel", oldMobitel, mobitel);
    }

    public void addPropertyChangeListener(PropertyChangeListener listener) {
        changeSupport.addPropertyChangeListener(listener);
    }

    public void removePropertyChangeListener(PropertyChangeListener listener) {
        changeSupport.removePropertyChangeListener(listener);
    }




}


